# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract_keys_request.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import protobuf.keys_filter_pb2 as keys__filter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ontract_keys_request.proto\x12\x0fwavesenterprise\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11keys_filter.proto\"\xe4\x01\n\x13\x43ontractKeysRequest\x12\x13\n\x0b\x63ontract_id\x18\x01 \x01(\t\x12*\n\x05limit\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12+\n\x06offset\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12-\n\x07matches\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\x0bkeys_filter\x18\x05 \x01(\x0b\x32\x1b.wavesenterprise.KeysFilterB[\n(com.wavesenterprise.transaction.protobufP\x01Z\x1bwavesenterprise.com/weproto\xaa\x02\x0fWavesEnterpriseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contract_keys_request_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.wavesenterprise.transaction.protobufP\001Z\033wavesenterprise.com/weproto\252\002\017WavesEnterprise'
  _globals['_CONTRACTKEYSREQUEST']._serialized_start=100
  _globals['_CONTRACTKEYSREQUEST']._serialized_end=328
# @@protoc_insertion_point(module_scope)
