# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_entry.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61ta_entry.proto\x12\x0fwavesenterprise\"\x80\x01\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\tint_value\x18\n \x01(\x03\x42\x02\x30\x01H\x00\x12\x14\n\nbool_value\x18\x0b \x01(\x08H\x00\x12\x16\n\x0c\x62inary_value\x18\x0c \x01(\x0cH\x00\x12\x16\n\x0cstring_value\x18\r \x01(\tH\x00\x42\x07\n\x05value\"<\n\rDataEntryList\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.wavesenterprise.DataEntry\"\xad\x01\n\x0c\x44\x61taEntryMap\x12G\n\rdataEntryList\x18\x01 \x03(\x0b\x32\x30.wavesenterprise.DataEntryMap.DataEntryListEntry\x1aT\n\x12\x44\x61taEntryListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.wavesenterprise.DataEntryList:\x02\x38\x01\x42[\n(com.wavesenterprise.transaction.protobufP\x01Z\x1bwavesenterprise.com/weproto\xaa\x02\x0fWavesEnterpriseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_entry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.wavesenterprise.transaction.protobufP\001Z\033wavesenterprise.com/weproto\252\002\017WavesEnterprise'
  _globals['_DATAENTRY'].fields_by_name['int_value']._options = None
  _globals['_DATAENTRY'].fields_by_name['int_value']._serialized_options = b'0\001'
  _globals['_DATAENTRYMAP_DATAENTRYLISTENTRY']._options = None
  _globals['_DATAENTRYMAP_DATAENTRYLISTENTRY']._serialized_options = b'8\001'
  _globals['_DATAENTRY']._serialized_start=38
  _globals['_DATAENTRY']._serialized_end=166
  _globals['_DATAENTRYLIST']._serialized_start=168
  _globals['_DATAENTRYLIST']._serialized_end=228
  _globals['_DATAENTRYMAP']._serialized_start=231
  _globals['_DATAENTRYMAP']._serialized_end=404
  _globals['_DATAENTRYMAP_DATAENTRYLISTENTRY']._serialized_start=320
  _globals['_DATAENTRYMAP_DATAENTRYLISTENTRY']._serialized_end=404
# @@protoc_insertion_point(module_scope)
