# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keys_filter.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11keys_filter.proto\x12\x0fwavesenterprise\"\x1a\n\nKeysFilter\x12\x0c\n\x04keys\x18\x01 \x03(\tB[\n(com.wavesenterprise.transaction.protobufP\x01Z\x1bwavesenterprise.com/weproto\xaa\x02\x0fWavesEnterpriseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keys_filter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.wavesenterprise.transaction.protobufP\001Z\033wavesenterprise.com/weproto\252\002\017WavesEnterprise'
  _globals['_KEYSFILTER']._serialized_start=38
  _globals['_KEYSFILTER']._serialized_end=64
# @@protoc_insertion_point(module_scope)
