# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract_asset_operation/contract_issue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-contract_asset_operation/contract_issue.proto\x12\x0fwavesenterprise\"\x8e\x01\n\rContractIssue\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x03\x12\x10\n\x08\x64\x65\x63imals\x18\x05 \x01(\x05\x12\x15\n\ris_reissuable\x18\x06 \x01(\x08\x12\r\n\x05nonce\x18\x07 \x01(\x05\x42\x62\n/com.wavesenterprise.transaction.protobuf.dockerP\x01Z\x1bwavesenterprise.com/weproto\xaa\x02\x0fWavesEnterpriseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contract_asset_operation.contract_issue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n/com.wavesenterprise.transaction.protobuf.dockerP\001Z\033wavesenterprise.com/weproto\252\002\017WavesEnterprise'
  _globals['_CONTRACTISSUE']._serialized_start=67
  _globals['_CONTRACTISSUE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
