# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract_asset_operation/contract_transfer_out.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4contract_asset_operation/contract_transfer_out.proto\x12\x0fwavesenterprise\x1a\x1egoogle/protobuf/wrappers.proto\"h\n\x13\x43ontractTransferOut\x12.\n\x08\x61sset_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x42\x62\n/com.wavesenterprise.transaction.protobuf.dockerP\x01Z\x1bwavesenterprise.com/weproto\xaa\x02\x0fWavesEnterpriseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contract_asset_operation.contract_transfer_out_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n/com.wavesenterprise.transaction.protobuf.dockerP\001Z\033wavesenterprise.com/weproto\252\002\017WavesEnterprise'
  _globals['_CONTRACTTRANSFEROUT']._serialized_start=105
  _globals['_CONTRACTTRANSFEROUT']._serialized_end=209
# @@protoc_insertion_point(module_scope)
