# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract_asset_operation/contract_cancel_lease.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4contract_asset_operation/contract_cancel_lease.proto\x12\x0fwavesenterprise\"&\n\x13\x43ontractCancelLease\x12\x0f\n\x07leaseId\x18\x01 \x01(\tBb\n/com.wavesenterprise.transaction.protobuf.dockerP\x01Z\x1bwavesenterprise.com/weproto\xaa\x02\x0fWavesEnterpriseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contract_asset_operation.contract_cancel_lease_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n/com.wavesenterprise.transaction.protobuf.dockerP\001Z\033wavesenterprise.com/weproto\252\002\017WavesEnterprise'
  _globals['_CONTRACTCANCELLEASE']._serialized_start=73
  _globals['_CONTRACTCANCELLEASE']._serialized_end=111
# @@protoc_insertion_point(module_scope)
