# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobuf.contract import contract_contract_service_pb2 as contract_dot_contract__contract__service__pb2
import protobuf.contract_keys_request_pb2 as contract__keys__request__pb2
import protobuf.contract_keys_response_pb2 as contract__keys__response__pb2


class ContractServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_stream(
                '/wavesenterprise.ContractService/Connect',
                request_serializer=contract_dot_contract__contract__service__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=contract_dot_contract__contract__service__pb2.ContractTransactionResponse.FromString,
                )
        self.CommitExecutionSuccess = channel.unary_unary(
                '/wavesenterprise.ContractService/CommitExecutionSuccess',
                request_serializer=contract_dot_contract__contract__service__pb2.ExecutionSuccessRequest.SerializeToString,
                response_deserializer=contract_dot_contract__contract__service__pb2.CommitExecutionResponse.FromString,
                )
        self.CommitExecutionError = channel.unary_unary(
                '/wavesenterprise.ContractService/CommitExecutionError',
                request_serializer=contract_dot_contract__contract__service__pb2.ExecutionErrorRequest.SerializeToString,
                response_deserializer=contract_dot_contract__contract__service__pb2.CommitExecutionResponse.FromString,
                )
        self.GetContractKeys = channel.unary_unary(
                '/wavesenterprise.ContractService/GetContractKeys',
                request_serializer=contract__keys__request__pb2.ContractKeysRequest.SerializeToString,
                response_deserializer=contract__keys__response__pb2.ContractKeysResponse.FromString,
                )
        self.GetContractKey = channel.unary_unary(
                '/wavesenterprise.ContractService/GetContractKey',
                request_serializer=contract_dot_contract__contract__service__pb2.ContractKeyRequest.SerializeToString,
                response_deserializer=contract_dot_contract__contract__service__pb2.ContractKeyResponse.FromString,
                )
        self.GetContractBalances = channel.unary_unary(
                '/wavesenterprise.ContractService/GetContractBalances',
                request_serializer=contract_dot_contract__contract__service__pb2.ContractBalancesRequest.SerializeToString,
                response_deserializer=contract_dot_contract__contract__service__pb2.ContractBalancesResponse.FromString,
                )
        self.CalculateAssetId = channel.unary_unary(
                '/wavesenterprise.ContractService/CalculateAssetId',
                request_serializer=contract_dot_contract__contract__service__pb2.CalculateAssetIdRequest.SerializeToString,
                response_deserializer=contract_dot_contract__contract__service__pb2.AssetId.FromString,
                )


class ContractServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitExecutionSuccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_det10000ails('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitExecutionError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContractKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContractKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContractBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateAssetId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContractServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=contract_dot_contract__contract__service__pb2.ConnectionRequest.FromString,
                    response_serializer=contract_dot_contract__contract__service__pb2.ContractTransactionResponse.SerializeToString,
            ),
            'CommitExecutionSuccess': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitExecutionSuccess,
                    request_deserializer=contract_dot_contract__contract__service__pb2.ExecutionSuccessRequest.FromString,
                    response_serializer=contract_dot_contract__contract__service__pb2.CommitExecutionResponse.SerializeToString,
            ),
            'CommitExecutionError': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitExecutionError,
                    request_deserializer=contract_dot_contract__contract__service__pb2.ExecutionErrorRequest.FromString,
                    response_serializer=contract_dot_contract__contract__service__pb2.CommitExecutionResponse.SerializeToString,
            ),
            'GetContractKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContractKeys,
                    request_deserializer=contract__keys__request__pb2.ContractKeysRequest.FromString,
                    response_serializer=contract__keys__response__pb2.ContractKeysResponse.SerializeToString,
            ),
            'GetContractKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContractKey,
                    request_deserializer=contract_dot_contract__contract__service__pb2.ContractKeyRequest.FromString,
                    response_serializer=contract_dot_contract__contract__service__pb2.ContractKeyResponse.SerializeToString,
            ),
            'GetContractBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContractBalances,
                    request_deserializer=contract_dot_contract__contract__service__pb2.ContractBalancesRequest.FromString,
                    response_serializer=contract_dot_contract__contract__service__pb2.ContractBalancesResponse.SerializeToString,
            ),
            'CalculateAssetId': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateAssetId,
                    request_deserializer=contract_dot_contract__contract__service__pb2.CalculateAssetIdRequest.FromString,
                    response_serializer=contract_dot_contract__contract__service__pb2.AssetId.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wavesenterprise.ContractService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContractService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/wavesenterprise.ContractService/Connect',
            contract_dot_contract__contract__service__pb2.ConnectionRequest.SerializeToString,
            contract_dot_contract__contract__service__pb2.ContractTransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitExecutionSuccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wavesenterprise.ContractService/CommitExecutionSuccess',
            contract_dot_contract__contract__service__pb2.ExecutionSuccessRequest.SerializeToString,
            contract_dot_contract__contract__service__pb2.CommitExecutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitExecutionError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wavesenterprise.ContractService/CommitExecutionError',
            contract_dot_contract__contract__service__pb2.ExecutionErrorRequest.SerializeToString,
            contract_dot_contract__contract__service__pb2.CommitExecutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContractKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wavesenterprise.ContractService/GetContractKeys',
            contract__keys__request__pb2.ContractKeysRequest.SerializeToString,
            contract__keys__response__pb2.ContractKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContractKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wavesenterprise.ContractService/GetContractKey',
            contract_dot_contract__contract__service__pb2.ContractKeyRequest.SerializeToString,
            contract_dot_contract__contract__service__pb2.ContractKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContractBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wavesenterprise.ContractService/GetContractBalances',
            contract_dot_contract__contract__service__pb2.ContractBalancesRequest.SerializeToString,
            contract_dot_contract__contract__service__pb2.ContractBalancesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateAssetId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wavesenterprise.ContractService/CalculateAssetId',
            contract_dot_contract__contract__service__pb2.CalculateAssetIdRequest.SerializeToString,
            contract_dot_contract__contract__service__pb2.AssetId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
